### ISSUE TITLE
Doesnt works in 2022.2.3

### ISSUE THREAD

**Issue by slim971** [bbo76/light.beewi#1]
Hello, i am using this components since many time, to control some old Beewi BLE lights, but when i upgraded from 2021.12.10 to 2022.2.3, it failed.
I got this error message : cannot import name 'Light' from 'homeassistant.components.light'

thanks a lot for helping
best regards

**Comment by bbo76** [comment]
Hi, sorry but with the new versions of HA it a little bit more complicated to maintain this project.
